### ISSUE TITLE
Oraichain is a visible chain, however xOCH doesn't show up?

### ISSUE THREAD

**Issue by 4coffeeihadbreakfast** [chainapsis/keplr-chain-registry#364] opened 2024-01-05 09:55 UTC
How can we add the xOCH token address to Keplr?

**Comment by HeesungB** [comment] 2024-01-05 13:16
Where can i add Oraichain?

**Comment by 4coffeeihadbreakfast** [comment] 2024-01-05 22:31
> Where can i add Oraichain?

Keplr -> hamburger menu (top left) -> Manage Chain Visibility -> (search for oraichain) -> click radio box

**Comment by claraexmachina** [comment] 2024-06-25 14:33
I think he was referring to on which app he can use Oraichain (to get the add chain pop up on their frontend). It seems like the issue is outdated so I will temporarily close this issue, but you can create new issue anytime if it still persists.

**Closed by claraexmachina** 2024-06-25 14:33 UTC
